add GET /api/categories
mxlro-star/nc-games pull request #2
Opened 2022-07-04 15:23 UTC by mxlro-star

2022-07-04 15:53 UTC, Rayhaan2k9 commented on controllers/categories.js
> +    .catch(() => res.status(500).send({ msg: "Internal Server Error" }));
I would put the 500 error in app.js and then just put .catch(next) on line 6

2022-07-04 15:53 UTC, Rayhaan2k9 commented on app.js
> +
Put your 500 error in this file :)

2022-07-04 15:54 UTC, Rayhaan2k9 requested changes
Have a look at the couple comments I left. Once you've changed these, send another PR :)

2022-07-05 10:54 UTC, karlaferry commented on __tests__/app.test.js
> +  describe("/api", () => {
Just a heads up, you will need to edit /api towards the end of the sprint (ticket 13) :)

2022-07-05 10:59 UTC, karlaferry commented on __tests__/app.test.js
> +            expect(body.slugs).toEqual(mockData.categoryData);
I would not recommend referencing the actual test data for any of the tests. Please try and check if the response you receive contains the necessary properties instead of directly referencing the test data.

2022-07-05 11:01 UTC, karlaferry commented on controllers/categories.js
> +    .then((slugs) => res.status(200).send({ slugs }))
Key should be `categories` instead of `slugs`

2022-07-05 11:05 UTC, karlaferry commented on listen.js
> +app.listen(9090);
Please add the necessary callback to check for errors.

2022-07-05 11:06 UTC, karlaferry requested changes
Please see comments :)

2022-07-05 11:33 UTC, karlaferry approved these changes
So much better :) Feel free to merge now :)

2022-07-05 11:38 UTC, merged